INSERT INTO cidade (id, nome) VALUES (1,'Assis');
INSERT INTO cidade (id, nome) VALUES (2,'Cornelio Procopio');
INSERT INTO cidade (id, nome) VALUES (3, 'Londrina');
INSERT INTO cidade (id, nome) VALUES (4, 'Maringá');
INSERT INTO cidade (id, nome) VALUES (5, 'Curitiba');
INSERT INTO cidade (id, nome) VALUES (6, 'Ponta Grossa');
INSERT INTO cidade (id, nome) VALUES (7, 'Cascavel');
INSERT INTO cidade (id, nome) VALUES (8, 'Foz do Iguaçu');
INSERT INTO cidade (id, nome) VALUES (9, 'Guarapuava');
INSERT INTO cidade (id, nome) VALUES (10, 'Paranaguá');
INSERT INTO cidade (id, nome) VALUES (11, 'Apucarana');
INSERT INTO cidade (id, nome) VALUES (12, 'Campo Mourão');
INSERT INTO cidade (id, nome) VALUES (13, 'Toledo');
INSERT INTO cidade (id, nome) VALUES (14, 'Arapongas');
INSERT INTO cidade (id, nome) VALUES (15, 'Umuarama');
INSERT INTO cidade (id, nome) VALUES (16, 'Sarandi');
INSERT INTO cidade (id, nome) VALUES (17, 'Colombo');
INSERT INTO cidade (id, nome) VALUES (18, 'Pinhais');
INSERT INTO cidade (id, nome) VALUES (19, 'São José dos Pinhais');
INSERT INTO cidade (id, nome) VALUES (20, 'Araucária');